Repository FalarzEdu/backend-ur-project, pull requests merged in 2024-12, with the labels that each got.

#20 Migrate JS into TS
  .gitignore
  app/Controllers/AdminController.php
  app/Controllers/UserController.php
  app/views/authentications/new.phtml
  app/views/home-users/new.phtml
  app/views/home/admin/index.phtml
  app/views/layouts/admin.phtml
  app/views/layouts/home.phtml
  app/views/layouts/homeAdmin.phtml
  app/views/layouts/homeUser.phtml
  app/views/layouts/login.phtml
  app/views/layouts/user.phtml
  eslint.config.mjs
  package.json
  public/assets/js/Controllers/admin.js
  public/assets/js/Controllers/admin.js.map
  public/assets/js/Controllers/login.js
  public/assets/js/Controllers/login.js.map
  public/assets/js/Controllers/user.js
  public/assets/js/Controllers/user.js.map
  public/assets/js/Models/Interaction.js
  public/assets/js/Models/Interaction.js.map
  public/assets/js/Models/Validation.js
  public/assets/js/Models/Validation.js.map
  public/assets/js/admin.js
  public/assets/js/login.js
  public/assets/ts/Controllers/admin.ts
  public/assets/ts/Controllers/login.ts
  public/assets/ts/Controllers/user.ts
  public/assets/ts/Models/Interaction.ts
  public/assets/ts/Models/Validation.ts
  public/assets/ts/homeUser.js
  public/assets/ts/login.js
  public/assets/ts/login.ts
  tests/Unit/Models/Users/UserTest.php
  tsconfig.json
  yarn.lock
Labels: enhancement, refactor

#28 @pablo/27/feature/feedback designe
  app/Controllers/FeedbacksController.php
  app/Models/Feedback.php
  app/Models/Message.php
  app/Models/User.php
  app/views/feedbacks/admin/index.phtml
  app/views/feedbacks/new.phtml
  app/views/feedbacks/user/index.phtml
  app/views/home-users/new.phtml
  app/views/layouts/admin.phtml
  app/views/layouts/application.phtml
  app/views/layouts/home.phtml
  app/views/layouts/homeAdmin.phtml
  app/views/layouts/homeUser.phtml
  app/views/layouts/user.phtml
  config/routes.php
  core/Database/ActiveRecord/Model.php
  core/Database/Database.php
  core/Http/Controllers/Controller.php
  database/schema.sql
  phpcs.xml
  public/assets/css/styles.css
  run
  tailwind.config.js
Labels: feature

#30 @pablo/29/bug/bug destroy
  app/Controllers/FeedbacksController.php
  app/Models/Feedback.php
  app/views/feedbacks/user/edit.phtml
  app/views/feedbacks/user/index.phtml
  app/views/feedbacks/user/new.phtml
  config/routes.php
  core/Http/Controllers/Controller.php
  public/assets/css/admin.css
  public/assets/css/homeUser.css
  public/assets/css/login.css
Labels: bug

#33 @pablo/32/feature/edit designe feedback
  app/views/feedbacks/user/edit.phtml
  app/views/feedbacks/user/index.phtml
  app/views/feedbacks/user/new.phtml
  public/assets/css/styles.css
Labels: feature
